# Generated by Django 3.1.7 on 2023-11-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0003_auto_20231120_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.CharField(max_length=250)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.issue')),
            ],
        ),
    ]
